# Generated by Django 4.2.3 on 2023-07-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='yugioh',
        ),
    ]
